# Generated by Django 6.0.2 on 2026-03-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tudo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
