# Generated by Django 6.0.2 on 2026-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudo', '0003_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='subject',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='list',
            name='textbox',
            field=models.CharField(max_length=510),
        ),
    ]
